name: Publish Docker image

on:
  release:
    types: [published]

jobs:
  docker:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - uses: actions-ecosystem/action-get-latest-tag@v1
        id: get-latest-tag
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: timwitzdam/gitsave:${{ steps.get-latest-tag.outputs.tag }}
